stages:
  pull_data:
    cmd: python src/pull_data.py
    deps:
      - config.yaml 
    outs:
      - data/partitions

  data_preparation:
    cmd: python src/data_preparation.py
    deps:
      - data/partitions
      - config.yaml
    outs:
      - data/splits/train
      - data/splits/val
      - data/splits/test

  train_model:
    cmd: python src/train_model.py
    deps:
      - data/splits/train
      - data/splits/val
      - config.yaml
    outs:
      - model/model.pth

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - model/model.pth
      - data/splits/test
      - config.yaml
    outs:
      - reports  # Keeps all previous reports
      - results  # Keeps all previous results
    